stages:
  - pdf
  - preview
  - deploy

build-pdf:
  image: aergus/latex:latest
  stage: pdf
  script:
    - latexmk -xelatex -synctex=1 -interaction=nonstopmode -file-line-error ./dissertation.tex
  artifacts:
    paths:
      - "*.pdf"
      - "*.log"

build-preview:
  image:
    name: debian:stable-slim
    entrypoint: [""]
  stage: preview
  before_script:
    - apt update
    - apt install -y --no-install-recommends imagemagick ghostscript
  script:
    - convert -density 600 -depth 8 -quality 100 "dissertation.pdf[0]" dissertation.jpg
  artifacts:
    paths:
      - "*.jpg"

pages:
  stage: deploy
  script:
    - mkdir public
    - cp dissertation.pdf public
    - cp dissertation.jpg public
  artifacts:
    paths:
      - public
  only:
    - master
